In [3]:
def my_function():
    "This print a string"
    print ("Hello from a function")

In [4]:
my_function()

Hello from a function


In [5]:
def printme(nama): # parameter # nama holds value Raka / nama saya adalah ....
        "This prints a nama string into this function"
        print(nama)

In [8]:
printme("Raka") # argument

Raka


In [9]:
printme("nama saya adalah ....")

nama saya adalah ....


In [18]:
def printme(nama, alamat): 
        "This prints a nama string into this function"
        print(nama)
        print(alamat)

In [19]:
printme("Raka","Semarang")

Raka
Semarang


In [20]:
printme(alamat="Semarang", nama="Raka")

Raka
Semarang


In [21]:
def printme(nama = "Raka", alamat = "Semarang"): 
        "This prints a nama string into this function"
        print(nama)
        print(alamat)
        return

In [22]:
printme()

Raka
Semarang


In [23]:
printme("Hacktiv8")

Hacktiv8
Semarang


In [24]:
printme(alamat = "jakarta")

Raka
jakarta


In [25]:
printme("Hacktiv8", "Jakarta")

Hacktiv8
Jakarta


In [30]:
def printinfo(argl, *vartuple):
    "This is a variable passed argument"
    print("Output is: ")
    print(argl)
    for var in vartuple:
        print(var)
    return;

In [31]:
printinfo(30)

Output is: 
30


In [32]:
printinfo(1, 2, 3, 4, 5, 6, 7, 8, 9)

Output is: 
1
2
3
4
5
6
7
8
9


In [35]:
sum = lambda arg1, vartuple: arg1 + vartuple;

In [36]:
sum(10, 20)

30

In [39]:
print("value of total:", sum(20, 20))

value of total: 40


In [41]:
def sum(arg1, arg2):
    total = arg1 + arg2
    total1 = total + 50
    return total, total1

In [42]:
sum(10, 20)

(30, 80)

In [57]:
kucing = 20

def jumlahHewan():
    kelinci = 30
    hewan = kucing + kelinci
    return hewan

def tambahHewan():
    anjing = 20
    tambahan = anjing + kucing
    return tambahan

In [58]:
jumlahHewan()

50

In [59]:
tambahHewan()

40

In [60]:
import sys

In [116]:
sys.path

['C:\\Users\\Asus\\Desktop',
 'C:\\Users\\Asus\\anaconda3\\python37.zip',
 'C:\\Users\\Asus\\anaconda3\\DLLs',
 'C:\\Users\\Asus\\anaconda3\\lib',
 'C:\\Users\\Asus\\anaconda3',
 '',
 'C:\\Users\\Asus\\anaconda3\\lib\\site-packages',
 'C:\\Users\\Asus\\anaconda3\\lib\\site-packages\\win32',
 'C:\\Users\\Asus\\anaconda3\\lib\\site-packages\\win32\\lib',
 'C:\\Users\\Asus\\anaconda3\\lib\\site-packages\\Pythonwin',
 'C:\\Users\\Asus\\anaconda3\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\Asus\\.ipython',
 'Users/Asus/Desktop/H8package',
 '/Users/Asus/Desktop/H8package/',
 '/Users/Asus/Desktop/H8package/']

In [117]:
sys.path.append(r'/Users/Asus/Desktop/H8package/')

In [118]:
sys.path

['C:\\Users\\Asus\\Desktop',
 'C:\\Users\\Asus\\anaconda3\\python37.zip',
 'C:\\Users\\Asus\\anaconda3\\DLLs',
 'C:\\Users\\Asus\\anaconda3\\lib',
 'C:\\Users\\Asus\\anaconda3',
 '',
 'C:\\Users\\Asus\\anaconda3\\lib\\site-packages',
 'C:\\Users\\Asus\\anaconda3\\lib\\site-packages\\win32',
 'C:\\Users\\Asus\\anaconda3\\lib\\site-packages\\win32\\lib',
 'C:\\Users\\Asus\\anaconda3\\lib\\site-packages\\Pythonwin',
 'C:\\Users\\Asus\\anaconda3\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\Asus\\.ipython',
 'Users/Asus/Desktop/H8package',
 '/Users/Asus/Desktop/H8package/',
 '/Users/Asus/Desktop/H8package/',
 '/Users/Asus/Desktop/H8package/']

In [119]:
import mod

In [120]:
mod.s

'Hacktiv9 Inalum for Data Science'

In [121]:
mod.a

[100, 200, 300]

In [122]:
mod.foo('raka')

raka


In [123]:
from mod import s, foo

In [124]:
s

'Hacktiv9 Inalum for Data Science'

In [125]:
foo('Raka')

Raka


In [126]:
from mod import s as string

In [127]:
string

'Hacktiv9 Inalum for Data Science'

In [128]:
import mod as my_module

In [129]:
my_module.a

[100, 200, 300]

In [133]:
my_module.s

'Hacktiv9 Inalum for Data Science'

In [134]:
import H8package.mod

H8package.mod.a

[100, 200, 300]

In [135]:
import H8package.mod import a

SyntaxError: invalid syntax (<ipython-input-135-9b0d723ae416>, line 1)

In [136]:
sys.path.append(r'/Users/Asus/Desktop/H8package/')

In [137]:
sys.path

['C:\\Users\\Asus\\Desktop',
 'C:\\Users\\Asus\\anaconda3\\python37.zip',
 'C:\\Users\\Asus\\anaconda3\\DLLs',
 'C:\\Users\\Asus\\anaconda3\\lib',
 'C:\\Users\\Asus\\anaconda3',
 '',
 'C:\\Users\\Asus\\anaconda3\\lib\\site-packages',
 'C:\\Users\\Asus\\anaconda3\\lib\\site-packages\\win32',
 'C:\\Users\\Asus\\anaconda3\\lib\\site-packages\\win32\\lib',
 'C:\\Users\\Asus\\anaconda3\\lib\\site-packages\\Pythonwin',
 'C:\\Users\\Asus\\anaconda3\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\Asus\\.ipython',
 'Users/Asus/Desktop/H8package',
 '/Users/Asus/Desktop/H8package/',
 '/Users/Asus/Desktop/H8package/',
 '/Users/Asus/Desktop/H8package/',
 '/Users/Asus/Desktop/H8package/']

In [138]:
import H8package.mod

In [139]:
sys.path.append(r'/Users/Asus/Desktop/')

In [140]:
import H8package.mod

H8package.mod.a

[100, 200, 300]

In [141]:
!pip --version

pip 20.0.2 from C:\Users\Asus\anaconda3\lib\site-packages\pip (python 3.7)



In [142]:
!pip install requests

In [143]:
conda install numpy

Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\Asus\anaconda3

  added / updated specs:
    - numpy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.8.3                |           py37_0         2.8 MB
    ------------------------------------------------------------
                                           Total:         2.8 MB

The following packages will be UPDATED:

  conda                                        4.8.2-py37_0 --> 4.8.3-py37_0




conda-4.8.3          | 2.8 MB    |            |   0% 
conda-4.8.3          | 2.8 MB    |            |   1% 
conda-4.8.3          | 2.8 MB    | 4          |   4% 
conda-4.8.3          | 2.8 MB    | 7          |   7% 
conda-4.8.3          | 2.8 MB    | #5         |  15% 
conda-4.8.3          | 2.8 MB    | #8         |  19% 
conda-4.8.3          | 2.8 MB    | ##9        |  30% 
conda-4.8.3

In [167]:
##Numpy (Numerical python)

In [145]:
import numpy as np

In [146]:
##Creating array

a = np.array([1, 2, 3])

In [147]:
a

array([1, 2, 3])

In [149]:
b = [1, 2, 3]

In [150]:
b

[1, 2, 3]

In [151]:
c = np.zeros(5)

In [152]:
print(c)

[0. 0. 0. 0. 0.]


In [153]:
d = np.ones(5)

In [154]:
print(d)

[1. 1. 1. 1. 1.]


In [156]:
np.arange(4)

array([0, 1, 2, 3])

In [157]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [158]:
np.arange(0, 20, 2)   #mulai 0 sd 20, kelipatan 2 (start, stop, step)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [159]:
arr=np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [160]:
print(arr)

[1 2 3 4 5 6 7 8]


In [161]:
np.append(arr, [1, 2])  #add

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [162]:
np.delete(arr, 1)   #delete

array([1, 3, 4, 5, 6, 7, 8])

In [163]:
arr = np.array ([2, 4, 1, 3, 7, 6, 8])

In [164]:
print(arr)

[2 4 1 3 7 6 8]


In [165]:
np.sort(arr)  #sorting

array([1, 2, 3, 4, 6, 7, 8])

In [170]:
## shape and Size

In [171]:
array_example = np.array([
    [[0, 1, 2, 3],
     [4, 5, 6, 7]],
    [[0, 1, 2, 3],
     [4, 5, 6, 7]],
    [[0, 1, 2, 3],
     [4, 5, 6, 7]]
])

In [172]:
print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [173]:
array_example.ndim

3

In [176]:
array_example.size

24

In [177]:
array_example.shape

(3, 2, 4)

In [178]:
# Reshape

In [179]:
a = np.arange(6)

print(a)

[0 1 2 3 4 5]


In [180]:
b = a.reshape(3, 2)

In [181]:
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [182]:
a.reshape(6, 1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [183]:
# convert 1D to 2D

In [184]:
a

array([0, 1, 2, 3, 4, 5])

In [185]:
a.shape

(6,)

In [186]:
a2 = a[np.newaxis]
print(a2)
print(a2.shape)

[[0 1 2 3 4 5]]
(1, 6)


In [187]:
row_vector = a[np.newaxis, :]
print(row_vector)
print(row_vector.shape)

[[0 1 2 3 4 5]]
(1, 6)


In [188]:
col_vector = a[:, np.newaxis]
print(col_vector)
print(col_vector.shape)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]
(6, 1)


In [189]:
print(a.shape)

(6,)


In [190]:
d = np.expand_dims(a, axis=1)
print(d)
print(d.shape)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]
(6, 1)


In [191]:
e = np.expand_dims(a, axis=0)
print(e)
print(e.shape)

[[0 1 2 3 4 5]]
(1, 6)


In [192]:
## indexing and slicing

In [193]:
data = np.array([1, 2, 3])

In [194]:
data[0]

1

In [195]:
data[1]

2

In [196]:
data[0:2]

array([1, 2])

In [197]:
data[1:]

array([2, 3])

In [198]:
data[-2]

2

In [199]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [200]:
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [201]:
a[a<8]

array([1, 2, 3, 4, 5, 6, 7])

In [202]:
a[a>=8]

array([ 8,  9, 10, 11, 12])

In [203]:
lebih_lima = (a >= 5)

a[lebih_lima]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [204]:
a[(a > 2) & (a < 11)]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [205]:
# Create array from existing data

In [206]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])


In [207]:
arr1 = arr[3:9]

In [208]:
print(arr1)

[4 5 6 7 8 9]


In [209]:
a_1 = np.array([[1, 1],
                [2, 2]])

print(a_1)

[[1 1]
 [2 2]]


In [210]:
a_2 = np.array([[3, 3],
                [4, 4]])

print(a_2)

[[3 3]
 [4 4]]


In [211]:
np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [212]:
np.hstack((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [213]:
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [214]:
np.hsplit(arr, 5)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([ 9, 10])]

In [215]:
# view dan copy

In [216]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [217]:
b = a.view()

In [218]:
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [219]:
c = a.copy()

In [220]:
print(c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [221]:
# basic array operations

In [222]:
a_1

array([[1, 1],
       [2, 2]])

In [223]:
a_2

array([[3, 3],
       [4, 4]])

In [224]:
a_2 = a_1

In [225]:
a_2 + a_1

array([[2, 2],
       [4, 4]])

In [226]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [227]:
arr.sum()

55

In [228]:
a_1

array([[1, 1],
       [2, 2]])

In [229]:
a_1.sum()

6

In [230]:
a_1.sum(axis=0)

array([3, 3])

In [231]:
a_1.sum(axis=1)

array([2, 4])

In [232]:
a_1 * 1.6

array([[1.6, 1.6],
       [3.2, 3.2]])

In [233]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [234]:
a.sum()

78

In [235]:
a.min()

1

In [236]:
a.max()

12

In [237]:
a.min(axis=0)

array([1, 2, 3, 4])

In [238]:
a.min(axis=1)

array([1, 5, 9])

In [239]:
np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [240]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [241]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [242]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [243]:
np.random.random((3,2))

array([[0.91107189, 0.23757548],
       [0.21974011, 0.62894032],
       [0.96897642, 0.57367707]])

In [244]:
# matrix arithmetic

In [245]:
data = np.array([[1, 2], [3, 4]])
print(data)

[[1 2]
 [3 4]]


In [246]:
ones = np.ones([2, 2])
print(ones)

[[1. 1.]
 [1. 1.]]


In [247]:
print(data + ones)

[[2. 3.]
 [4. 5.]]


In [249]:
ones_row = np.ones([1, 2])
print(ones_row)

[[1. 1.]]


In [250]:
data + ones_row

array([[2., 3.],
       [4., 5.]])

In [251]:
a_1 = np.array([[1, 2, 3], [4, 5, 6]])
print(a_1)

a_2 = np.array([[7, 8], [9, 10], [11, 12]])
print(a_2)

[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]


In [252]:
print(a_1.shape)
print(a_2.shape)

(2, 3)
(3, 2)


In [253]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

In [254]:
data = np.array([[1, 2], [3, 4], [5, 6]])

In [255]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [256]:
data[0,1]

2

In [257]:
data[1,1]

4

In [258]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [259]:
data[0:2]

array([[1, 2],
       [3, 4]])

In [260]:
data[0:2, 1]

array([2, 4])

In [261]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [262]:
data.max()

6

In [263]:
data.min()

1

In [264]:
data.sum()

21

In [265]:
data.max(axis=1)

array([2, 4, 6])

In [266]:
data.max(axis=0)

array([5, 6])

In [267]:
# transposing and reshaping

In [268]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [269]:
data.T

array([[1, 3, 5],
       [2, 4, 6]])

In [270]:
data_col = np.array([[1, 2, 3, 4, 5, 6]]).T
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [271]:
data_col.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [272]:
data_col.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [273]:
arr = np.arange(6).reshape((2, 3))

In [274]:
print(arr)

[[0 1 2]
 [3 4 5]]


In [275]:
# ND Array

In [276]:
ndarr = np.array([[[1, 2], [3, 4]],
                 [[5, 6], [7, 8]]])

In [277]:
ndarr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [278]:
np.ones((4,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [279]:
np.zeros((4,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [280]:
np.random.random((4,3,2))

array([[[0.24422666, 0.77725084],
        [0.81749712, 0.84979007],
        [0.85601925, 0.71753151]],

       [[0.28709634, 0.90960871],
        [0.51512708, 0.44776094],
        [0.19956837, 0.69127891]],

       [[0.19669194, 0.78282284],
        [0.12569535, 0.46411434],
        [0.94209591, 0.76667348]],

       [[0.89831843, 0.13536475],
        [0.97125968, 0.8877003 ],
        [0.31988485, 0.78676971]]])

In [281]:
# flatton

In [282]:
ndarr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [283]:
ndarr.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])